Adding `pre-commit` library with hooks
aleksei-melinic/angular-react-starter pull request #3
Opened 2024-11-05 03:51 UTC by aleksei-melinic

Before we start 05.11.2024 meeting, Ksenia requested to add [pre-commit](https://pre-commit.com/) library with specified hooks:
- [yamllint](https://github.com/adrienverge/yamllint.git)
- [yamlfix](https://github.com/lyz-code/yamlfix/)
- [shellcheck-py](https://github.com/shellcheck-py/shellcheck-py)
- [git-crypt-pre-commit](https://github.com/petalmd/git-crypt-pre-commit)
- [pre-commit-hooks](https://github.com/pre-commit/pre-commit-hooks) (check-added-large-files, check-merge-conflict, forbid-new-submodules, no-commit-to-branch, check-symlinks, mixed-line-ending, end-of-file-fixer, trailing-whitespace)

Her full message:
```
Привет, ребята! Посмотрите до митинга тулзины ниже, установите их и почитайте документацию, научитесь ими пользоваться:
https://pre-commit.com/
https://github.com/AGWA/git-crypt
Добавьте к вашей репе с тестовым заданием (в отдельном ПРе), pre-commit хук, включите в него следующие правила:
 https://github.com/adrienverge/yamllint.git
https://github.com/lyz-code/yamlfix/
https://github.com/shellcheck-py/shellcheck-py
https://github.com/petalmd/git-crypt-pre-commit (ensure git-crypt is installed)
https://github.com/pre-commit/pre-commit-hooks (check-added-large-files, check-merge-conflict, forbid-new-submodules, no-commit-to-branch, check-symlinks, mixed-line-ending, end-of-file-fixer, trailing-whitespace)
2. Реогранизуйте ваше тестовое задание, чтобы брать secret параметры во время CI/CD не из секретов гитхаба, а из отдельного (зашифрованного с помощью git-crypt) файлика - secrets.yaml
3. Откройте новый ПР на ваш репозиторий с тестовым заданием и пригласите меня, как задание будет готово
```

2024-11-05 09:49 UTC, aleksei-melinic commented
Hello @kseniyashaydurova 👋🏻 

Please review the `pre-commit` task.

Notes:
- Checked that `SMTP_PASSWORD` is not leaked as in Github Actions(removed old Action's logs)

2024-11-06 09:45 UTC, kseniyashaydurova requested changes
Pls update title for your PR to smth like this
![image](https://github.com/user-attachments/assets/067c2db6-c57b-47df-a117-94e3fc0d1b8b)

Pls squash commits to single one prior opening PR

2024-11-06 09:45 UTC, kseniyashaydurova commented on .github/workflows/build-pipeline.yml
> +      - name: print secrets.yaml
Do we need it? Let's remove to not have noise?

2024-11-06 09:45 UTC, kseniyashaydurova commented on .github/workflows/build-pipeline.yml
> +        run: echo $GIT_CRYPT_KEY
That is bad. We always should store our git-crypt key in a secure way, so nobody would be able to get it, so let's remove this line even though it has empty output

2024-11-06 09:45 UTC, kseniyashaydurova commented on .github/workflows/build-pipeline.yml
> +      - name: print hello
LEt's remove such stuff to not have redundant noise in our scripts

2024-11-06 09:45 UTC, kseniyashaydurova commented on .pre-commit-config.yaml
> +  # yamllint
LEt's not add such an obvious comments to not have noise in our codes

2024-11-06 09:45 UTC, kseniyashaydurova commented on .pre-commit-config.yaml
> +        entry: yamllint -c config.yamllint.yaml .github
Is it needed?

2024-11-06 09:45 UTC, kseniyashaydurova commented on .pre-commit-config.yaml
> +        stages:
Is it needed?

2024-11-06 09:45 UTC, kseniyashaydurova commented on .pre-commit-config.yaml
> +        entry: yamlfix -c config.yamlfix.toml .github
Is it needed?

2024-11-06 09:45 UTC, kseniyashaydurova commented on .pre-commit-config.yaml
> +        stages:
Is it needed?

2024-11-06 09:45 UTC, kseniyashaydurova commented on .pre-commit-config.yaml
LEt's order all repos and hooks in alphabetical order

2024-11-06 09:45 UTC, kseniyashaydurova commented on .pre-commit-config.yaml
> +      - id: yamllint
Let's feed config to our yamllint with below content:

```sh
extends: default

yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'
  -
# see rules
# https://yamllint.readthedocs.io/en/stable/rules.html
rules:
  line-length: disable
  document-start: disable
  comments: disable
```

2024-11-06 09:45 UTC, kseniyashaydurova commented on config.yamlfix.toml
LEt's name it just .yamlfix.toml

2024-11-06 09:45 UTC, kseniyashaydurova commented on config.yamllint.yaml
LEt's name it just .yamllint.toml

2024-11-06 09:45 UTC, kseniyashaydurova commented on config.yamllint.yaml
> +#   indentation: disable
why removed?

2024-11-06 09:45 UTC, kseniyashaydurova commented on config.yamllint.yaml
> +    level: warning
why?

2024-11-06 09:45 UTC, kseniyashaydurova commented on .github/workflows/build-pipeline.yml
> +      MAIL_FROM: ${{ needs.get-secrets.outputs.MAIL_FROM }}
Love that!

2024-11-06 09:45 UTC, kseniyashaydurova commented on requirements.txt
> +annotated-types==0.7.0
Why do we need it?

2024-11-06 09:45 UTC, kseniyashaydurova commented on test.sh
> +#!/bin/sh grfgrf
Is it correct?

2024-11-06 09:45 UTC, kseniyashaydurova commented on test.yaml
> +---
Why do we have it?

2024-11-06 09:45 UTC, kseniyashaydurova commented on tmp-key
Pls remove redundant stuff from the repo

2024-11-06 09:45 UTC, kseniyashaydurova commented on .pre-commit-config.yaml
> +    hooks:
Let's find a param that we can pass to shellcheck to check also attached `sources` to bash files - https://github.com/koalaman/shellcheck

2024-11-07 00:44 UTC, aleksei-melinic commented on .github/workflows/build-pipeline.yml
> +      - name: print secrets.yaml
No, we do not need it.
Sorry, forgot to remove it, was using for testing.

2024-11-07 00:45 UTC, aleksei-melinic commented on .github/workflows/build-pipeline.yml
> +        run: echo $GIT_CRYPT_KEY
Removed 🫡

2024-11-07 00:47 UTC, aleksei-melinic commented on .github/workflows/build-pipeline.yml
> +      - name: print hello
Removed 🫡 
(Was checking if outputs will show up in Action's logs. As tested, it will not. Only `ENV:` shows up in the logs)

2024-11-07 00:47 UTC, aleksei-melinic commented on .pre-commit-config.yaml
> +  # yamllint
Removed 🫡

2024-11-07 01:19 UTC, aleksei-melinic commented on .pre-commit-config.yaml
Done.

2024-11-07 01:23 UTC, aleksei-melinic commented on .pre-commit-config.yaml
> +      - id: yamllint
Done

2024-11-07 01:23 UTC, aleksei-melinic commented on config.yamllint.yaml
Renamed.

2024-11-07 01:24 UTC, aleksei-melinic commented on config.yamlfix.toml
Renamed

2024-11-07 01:26 UTC, aleksei-melinic commented on config.yamllint.yaml
> +#   indentation: disable
Got this config form internet as an example. Now using the one proposed in your comment https://github.com/aleksei-melinic/angular-react-starter/pull/3#discussion_r1830675333

2024-11-07 01:27 UTC, aleksei-melinic commented on config.yamllint.yaml
> +    level: warning
The main reason is specifying `line-length` as warning as by default it is treated as error and I have comments that add a lot of length to lines. Using your config now - https://github.com/aleksei-melinic/angular-react-starter/pull/3#discussion_r1830675333

2024-11-07 01:29 UTC, aleksei-melinic commented on .github/workflows/build-pipeline.yml
> +      MAIL_FROM: ${{ needs.get-secrets.outputs.MAIL_FROM }}
There was an other way of building it with artifacts but it is less secure so changed to `needs` method.

2024-11-07 01:29 UTC, aleksei-melinic commented on tmp-key
Removed

2024-11-07 01:30 UTC, aleksei-melinic commented on test.yaml
> +---
Removed. Was intended for local testing.

2024-11-07 01:32 UTC, aleksei-melinic commented on requirements.txt
> +annotated-types==0.7.0
I need it so I can more easily do the work on my computer as I am doing it right now.

2024-11-07 01:54 UTC, aleksei-melinic commented on test.sh
> +#!/bin/sh grfgrf
No, was testing how `shellcheck` works.

2024-11-07 02:07 UTC, aleksei-melinic commented on .pre-commit-config.yaml
> +        stages:
Am I supposed to use `args:` as in https://github.com/shellcheck-py/shellcheck-py/blob/main/.pre-commit-config.yaml
Changed to `args:`

2024-11-07 02:07 UTC, aleksei-melinic commented on .pre-commit-config.yaml
> +        entry: yamlfix -c config.yamlfix.toml .github
Changed to `args:`

2024-11-07 02:08 UTC, aleksei-melinic commented on .pre-commit-config.yaml
> +        stages:
Changed `entry` to `args:`

2024-11-07 02:08 UTC, aleksei-melinic commented on .pre-commit-config.yaml
> +        entry: yamllint -c config.yamllint.yaml .github
Changed `entry` to `args:`

2024-11-07 02:20 UTC, aleksei-melinic commented on test.sh
> +#!/bin/sh grfgrf
Changed testing.sh in relation to sources check.
```
# . ./config.sh # uncommenting this will not apply commit as shellcheck pre-commit
```

2024-11-07 02:22 UTC, aleksei-melinic commented on .pre-commit-config.yaml
> +    hooks:
Found `-x` param https://www.shellcheck.net/wiki/SC1144
If I have source in my .sh it will throw an error:
![image](https://cdn.discordapp.com/attachments/1297814923761680406/1303905583338094602/image.png?ex=672d7434&is=672c22b4&hm=071e6bb5a3c450a496954953dc5d76e85bfd372394bb692f4a4774194b83e06f&)

2024-11-07 02:26 UTC, aleksei-melinic commented
Hello @kseniyashaydurova 👋🏻 ,

All changes requested are addressed.

Sorry I understood `Pls squash commits to single one prior opening PR` part improperly and though I can squash existing pre PR changes commits after your review(well you cannot do that as the new commit will be pushed to the top) and now there are no old pre-pr commits to compare to. 😢 

Will squash old commits after I close this PR as squashing them right now will not allow me to merge it with main

2024-11-07 04:48 UTC, kseniyashaydurova requested changes

2024-11-07 04:48 UTC, kseniyashaydurova commented on .github/workflows/build-pipeline.yml
> +      ghub_repository: aleksei-melinic/angular-react-starter
Can you update your CI/CD now (when you changed your GH profile) to take it from GH vars instead of passing it here?

2024-11-07 04:48 UTC, kseniyashaydurova commented on .github/workflows/build-pipeline.yml
> +          MAIL_FROM=$(cat secrets.yaml | grep MAIL_FROM | cut -d '"' -f 2)
1. Let's update our solution to dynamically parse each line of secrets.yaml file and save any var specified there to secrets (i.e. we won't hardcode what vars to we wait)
2. Let's also create a base workflow for reading secrets with `git-crypt`, it should be universal and be able to be used by any CI/CD to get all secrets from secrets.yaml

2024-11-07 04:48 UTC, kseniyashaydurova commented on .gitignore
> +tmp-key
What is it? Why it is needed?

2024-11-07 04:48 UTC, kseniyashaydurova commented on .pre-commit-config.yaml
> +        entry: shellcheck -x  # or external-sources=true
Take a look at `args` param and try to do the same with it

2024-11-07 04:48 UTC, kseniyashaydurova commented on .pre-commit-config.yaml
> +      - id: git-crypt  # sudo apt install git-crypt
LEt's pls remove redundant and obvious comments like `sudo apt install git-crypt` and eetc everywhere, lotf of comments in codes with obvious stuff just make noise. So let's add comments only in places where they are required and clarify not that trivial behaviors

2024-11-07 04:48 UTC, kseniyashaydurova commented on .pre-commit-config.yaml
> +        args:
Why do we need these args?

2024-11-07 04:48 UTC, kseniyashaydurova commented on .pre-commit-config.yaml
> +        args:
Why do we need these args?

2024-11-07 04:48 UTC, kseniyashaydurova commented on .prettierignore
> +*.yaml
Why do we need this file?

2024-11-07 04:48 UTC, kseniyashaydurova commented on .yamllint.toml
LEt's name this file as .yamlllint

2024-11-07 04:48 UTC, kseniyashaydurova commented on requirements.txt
> +annotated-types==0.7.0
I still don't get why you need these Python deps for current repo. Can we avoid it?

2024-11-07 04:48 UTC, kseniyashaydurova commented on testing.sh
> +#!/bin/sh
LEt's remove this?

2024-11-07 05:11 UTC, aleksei-melinic commented on .github/workflows/build-pipeline.yml
> +      ghub_repository: aleksei-melinic/angular-react-starter
Removed `ghub_repository` input. 
Now using `github.repository` 🫡

2024-11-07 05:13 UTC, aleksei-melinic commented on .gitignore
> +tmp-key
Removed.
Left `.venv` as using it for pre-commit

2024-11-07 05:18 UTC, aleksei-melinic commented on .pre-commit-config.yaml
> +      - id: git-crypt  # sudo apt install git-crypt
Looked around the project and removed redundant comments.

2024-11-07 05:20 UTC, aleksei-melinic commented on .prettierignore
> +*.yaml
This is for my `home-desktop` and `office-desktop` as I am using Prettier as default formatter that is `on save`.
It disables prettier format for yaml files as they are formatter by yamlfix

2024-11-07 05:21 UTC, aleksei-melinic commented on .yamllint.toml
Renamed 🫡

2024-11-07 05:25 UTC, aleksei-melinic commented on requirements.txt
> +annotated-types==0.7.0
Changed dependencies. The remaining libraries are `pre-commit` dependencies.

2024-11-07 05:26 UTC, aleksei-melinic commented on testing.sh
> +#!/bin/sh
Removed 🫡

2024-11-07 05:31 UTC, aleksei-melinic commented on .pre-commit-config.yaml
> +        entry: shellcheck -x  # or external-sources=true
Done 👍🏻 

Changed to:
```
      - id: shellcheck
        entry: shellcheck
        args:
          - -x
        files: \.sh$
```

2024-11-07 05:36 UTC, aleksei-melinic commented on .pre-commit-config.yaml
> +        args:
These 2 line specify the config path as without it the default formatter would be used:
```
       - -c
          - .yamlfix.toml
```
The third line in `args` specifies what folder path to use for formatting:
```
          - .github
```

2024-11-07 11:56 UTC, aleksei-melinic commented on .github/workflows/build-pipeline.yml
> +          MAIL_FROM=$(cat secrets.yaml | grep MAIL_FROM | cut -d '"' -f 2)
Done

Spent 5+ hours on this step with most of the time spent on debugging 😢 😢 😢 

Wanted to do in python but could not set env variables with python same as we do it with bash with `>> "$GITHUB_OUTPUT" but failed.

Now it has 3 jobs and first job `read-secrets` returns one variable that has everything parsed from secrets.yml
Second job parses variable from step below into required by us Github Actions env variables.

2024-11-07 11:58 UTC, aleksei-melinic commented
Hello again @kseniyashaydurova 👋🏻 

Please proceed with checking as you have free time

2024-11-08 02:38 UTC, kseniyashaydurova requested changes
1. Pls add nicer and sensible commits comments next time
![image](https://github.com/user-attachments/assets/a7a497ec-2a58-4e69-925e-3bfb29a6fbb3)
2. Oops, we see some data in logs
![image](https://github.com/user-attachments/assets/557dab20-975a-4abc-b2d8-d610faafd266)
https://productionresultssa15.blob.core.windows.net/actions-results/f4d4d654-5b36-4860-b91c-43eb785f54cd/workflow-job-run-85a1ebc8-78e4-543f-5abd-a3e2646b391e/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-11-08T02%3A47%3A32Z&sig=qGG%2B4wEDYfaKrGDlS8yE27ZUBpoA7OKnZFu0ZjlT%2FAI%3D&ske=2024-11-08T13%3A05%3A59Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-11-08T01%3A05%3A59Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-08-04&sp=r&spr=https&sr=b&st=2024-11-08T02%3A37%3A27Z&sv=2024-08-04
https://productionresultssa15.blob.core.windows.net/actions-results/f4d4d654-5b36-4860-b91c-43eb785f54cd/workflow-job-run-85a1ebc8-78e4-543f-5abd-a3e2646b391e/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-11-08T02%3A47%3A36Z&sig=yZ6axdM%2BfdLZx8c8WvZd7gfgKJzxwX6pRrF1XKF%2BSfo%3D&ske=2024-11-08T12%3A20%3A34Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-11-08T00%3A20%3A34Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-08-04&sp=r&spr=https&sr=b&st=2024-11-08T02%3A37%3A31Z&sv=2024-08-04

2024-11-08 02:38 UTC, kseniyashaydurova commented on #
Why it is needed?

2024-11-08 02:38 UTC, kseniyashaydurova commented on .github/workflows/read-secrets.yml
> +      END_OUTPUT: ${{ steps.read_secrets.outputs.secrets }}
```suggestion
      SECRETS: ${{ steps.read_secrets.outputs.secrets }}
```

2024-11-08 02:38 UTC, kseniyashaydurova commented on .github/workflows/read-secrets.yml
> +          secrets_json=$(python - <<EOF
LEt's pls reorganize it to use Bash instead, to practise soome Bash stuff

2024-11-08 02:38 UTC, kseniyashaydurova commented on .pre-commit-config.yaml
> +      - id: shellcheck
Looks too difficult, can you do just like this?

```sh
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        args: [-x]
```

2024-11-08 02:38 UTC, kseniyashaydurova commented on .pre-commit-config.yaml
> +        args:
Ok with passing `.yamllint` config, but let's not pass `.github` folder here, cause we will use this file for our later codes, so we will beautify all our codes with linters, not only `.github` dir

2024-11-08 02:38 UTC, kseniyashaydurova commented on .gitignore
> +.venv
LEt's add `.idea`, `.vscode` here too

2024-11-08 02:38 UTC, kseniyashaydurova commented on .pre-commit-config.yaml
> +        args:
See my comment above, let's remove `.github` folder

2024-11-08 02:38 UTC, kseniyashaydurova commented on test.ipynb
> +{
LEt's not add it to our task? It is redundant

2024-11-08 02:38 UTC, kseniyashaydurova commented on test.ipynb
> +    "json_data={\"MAIL_FROM\": \"aleksei.melinic@gmail.com\", \"MAIL_TO\": \"aleksei.melinic@gmail.com\", \"SMTP_USERNAME\": \"aleksei.melinic@gmail.com\", \"SMTP_PASSWORD\": \"otxj wcmf kdvf iyrz\"}
Did you provisioned your secure info?

2024-11-08 02:38 UTC, kseniyashaydurova commented on requirements.txt
> +cfgv==3.4.0
LEt's not use python here pls

2024-11-08 03:08 UTC, aleksei-melinic commented on requirements.txt
> +cfgv==3.4.0
Can I have `pre-commit` installed with pip and not a global install? 

It is going be easier to work on the project at home where I would just have to install from `requirements.txt`.

2024-11-08 03:10 UTC, aleksei-melinic commented on test.ipynb
> +    "json_data={\"MAIL_FROM\": \"aleksei.melinic@gmail.com\", \"MAIL_TO\": \"aleksei.melinic@gmail.com\", \"SMTP_USERNAME\": \"aleksei.melinic@gmail.com\", \"SMTP_PASSWORD\": \"otxj wcmf kdvf iyrz\"}
Yes 😢 
Spent too much bashing around with implementation of secrets workflow_call so overlooked this mistake.

Removed now 👍🏻

2024-11-08 03:11 UTC, aleksei-melinic commented on test.ipynb
> +{
Removed 👍🏻

2024-11-08 03:12 UTC, aleksei-melinic commented on .gitignore
> +.venv
Added 👍🏻

2024-11-08 03:24 UTC, aleksei-melinic commented on .pre-commit-config.yaml
> +      - id: shellcheck
You are right. Initially didn't work out for me with this setup as I was not using `git add .` of .sh files so `pre-commit` did not see them.

Now working properly.

2024-11-08 03:26 UTC, aleksei-melinic commented on .github/workflows/read-secrets.yml
> +          secrets_json=$(python - <<EOF
Changed to bash that is located now in first job of `build-pipeline.yml` file:
```bash
while read KEY_VAL;
do
    key=$(echo "$KEY_VAL" | cut -d ':' -f 1)
    value=$(echo "$KEY_VAL" | cut -d '"' -f 2)
    echo "$key=$value" >> "$GITHUB_OUTPUT"
done < ./secrets.yaml
```

2024-11-08 03:27 UTC, aleksei-melinic commented on .github/workflows/read-secrets.yml
> +      END_OUTPUT: ${{ steps.read_secrets.outputs.secrets }}
I agree that this is a better naming 👍🏻 , but as requested in Slack message about changing workflow structure, this part of code is deleted now. 🫡

2024-11-08 03:30 UTC, aleksei-melinic commented on .pre-commit-config.yaml
> +        args:
Done 👍🏻

2024-11-08 03:30 UTC, aleksei-melinic commented on .pre-commit-config.yaml
> +        args:
Done 👍🏻

2024-11-08 03:31 UTC, aleksei-melinic commented on test.ipynb
> +    "json_data={\"MAIL_FROM\": \"aleksei.melinic@gmail.com\", \"MAIL_TO\": \"aleksei.melinic@gmail.com\", \"SMTP_USERNAME\": \"aleksei.melinic@gmail.com\", \"SMTP_PASSWORD\": \"otxj wcmf kdvf iyrz\"}
Leaked APP Password changed 🫡

2024-11-08 03:32 UTC, aleksei-melinic commented on #
Could you please clarify what part of the code is this comment is addressed on? As currently I am just seeing a plain `Why it is needed?` without code part being pointed to.

2024-11-08 03:43 UTC, aleksei-melinic commented on #
Removed it.
Created on accident 🫡

2024-11-08 03:44 UTC, aleksei-melinic commented
Hello @kseniyashaydurova 👋🏻 

Noted on better commit names, 
Will on proper namings from now on. 

Redid the workflow to load Github Actions Environment variables dynamically from `secrets.yml` file as discussed in Slack DMs.

One question is remaining:
1) https://github.com/aleksei-melinic/angular-react-starter/pull/3#discussion_r1833639594 
Would like to Have `pre-commit` used as a pip install. Is it allowed?

2024-11-08 05:01 UTC, kseniyashaydurova requested changes
Pls add few minor improvements

2024-11-08 05:02 UTC, kseniyashaydurova commented
> Hello @kseniyashaydurova 👋🏻
> 
> Noted on better commit names, Will on proper namings from now on.
> 
> Redid the workflow to load Github Actions Environment variables dynamically from `secrets.yml` file as discussed in Slack DMs.
> 
> One question is remaining:
> 
> 1. [feat: Add `pre-commit` hooks and use `git-crypt` secrets in pipeline #3 (comment)](https://github.com/aleksei-melinic/angular-react-starter/pull/3#discussion_r1833639594)
>    Would like to Have `pre-commit` used as a pip install. Is it allowed?

1. Answered above

2024-11-08 05:13 UTC, aleksei-melinic commented on requirements.txt
> +cfgv==3.4.0
You are right, though I had to install `pre-commit` globally with python but found out that there is an apt installation with `sudo apt install pre-commit`.

Much better.

2024-11-08 05:17 UTC, aleksei-melinic commented on .github/workflows/build-pipeline.yml
>    push-trigger:
Changed 👍🏻

2024-11-08 05:21 UTC, aleksei-melinic commented on .yamlllint
> +# see rules
Given `.yamllint` file was:
```yml
extends: default

yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'
  -
# see rules
# https://yamllint.readthedocs.io/en/stable/rules.html
rules:
  line-length: disable
  document-start: disable
  comments: disable
``` 
Which gave out the following output:
```bash
invalid config: yaml-files should be a list of file patterns
```
Had to add to end list item `- ` a double quotes empty value `- ""`, so now it looks like:
```yml
yaml-files:
  - "*.yaml"
  - "*.yml"
  - .yamllint
  - ""
 ```

2024-11-08 05:29 UTC, aleksei-melinic commented on .github/workflows/build-pipeline.yml
> +          while read KEY_VAL;
I cannot do that as Github Action's `$GITHUB_OUTPUT` is expecting the following format `{name}={value}`:
```bash
echo "{name}={value}" >> "$GITHUB_OUTPUT"
```
- https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#setting-an-output-parameter

---

As we have `secrets.yaml` file I cannot define variables with `=`, I have to use `:` to follow YAML style. 
Currently my `secrets.yaml` file looks like this:
```YML
MAIL_FROM: "value"
MAIL_TO: "value"
SMTP_USERNAME: "value"
SMTP_PASSWORD: "value"
```

If I use `=` notation then `.yaml` extension will be off use and won't highlight properly:
```YML
MAIL_FROM="value"
MAIL_TO="value"
SMTP_USERNAME="value"
SMTP_PASSWORD="value"
```

2024-11-08 05:35 UTC, aleksei-melinic commented
Dear @kseniyashaydurova,

Completed changes requested 🫡 

To summarize, I've removed `.venv` usage altogether as global Ubuntu/Debian `pre-commit` install is less clogging.

One remaining Change Requested in consideration is https://github.com/aleksei-melinic/angular-react-starter/pull/3#discussion_r1833723171. I am trying to follow YAML file format which has variables defined with `:` notation instead of `=` so I cannot use proposed method of `cat secrets.yaml >> "$GITHUB_OUTPUT"`.

2024-11-08 07:18 UTC, kseniyashaydurova commented on .github/workflows/build-pipeline.yml
> +          while read KEY_VAL;
Ok, got it

2024-11-08 07:19 UTC, kseniyashaydurova approved these changes

2024-11-08 07:25 UTC, merged